[package]
name = "museum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.3", features = ["wayland"]}
geo = "0.26.0"
geo-clipper = "0.8.0"
